import Plan from "../models/Plan.js";
import User from "../models/User.js";
import { generatePlan } from "../services/aiService.js";

export const createPlan = async (req, res) => {
  try {
    console.log('🔍 [PLAN CONTROLLER] createPlan called');
    console.log('🔍 [PLAN CONTROLLER] User from auth:', req.user);
    console.log('🔍 [PLAN CONTROLLER] Request body:', req.body);

    const userId = req.user.id;
    const { answers } = req.body;

    console.log('🔍 [PLAN CONTROLLER] User ID:', userId);
    console.log('🔍 [PLAN CONTROLLER] Answers received:', answers);

    if (!answers) {
      console.log('🔍 [PLAN CONTROLLER] ERROR: No answers provided');
      return res.status(400).json({ message: "Answers required" });
    }

    const user = await User.findById(userId);
    if (!user) {
      console.log('🔍 [PLAN CONTROLLER] ERROR: User not found with ID:', userId);
      return res.status(404).json({ message: "User not found" });
    }

    console.log('🔍 [PLAN CONTROLLER] User found:', user.name);

    // Call AI service (includes fallback internally)
    console.log('🔍 [PLAN CONTROLLER] Calling AI service...');
    const { dietPlan, exercisePlan, meta } = await generatePlan(answers);
    console.log('🔍 [PLAN CONTROLLER] AI service completed');

    // ✅ UPDATED: Create plan with BPM included
    const plan = await Plan.create({
      user: user._id,
      answers,
      dietPlan,
      exercisePlan,
      aiMeta: meta,
      notes: "Generated by AI service",
      bpm: answers.bpm // ✅ NEW: Store BPM in plan as well
    });

    console.log('🔍 [PLAN CONTROLLER] Plan created successfully:', plan._id);
    console.log('🔍 [PLAN CONTROLLER] Plan BPM saved:', answers.bpm);

    // ✅ UPDATED: Save BPM to user profile
    user.latestPlan = plan._id;
    if (answers.age) user.age = parseInt(answers.age) || user.age;
    if (answers.weight) user.weight = parseFloat(answers.weight) || user.weight;
    if (answers.height) user.height = parseFloat(answers.height) || user.height;
    if (answers.activity) user.activity = answers.activity;
    if (answers.fitnessGoal) user.fitnessGoal = answers.fitnessGoal;
    if (answers.conditions) user.conditions = answers.conditions;
    
    // ✅ NEW: Save BPM to user
    if (answers.bpm) {
      user.bpm = parseInt(answers.bpm);
      console.log('🔍 [PLAN CONTROLLER] Saved BPM to user:', answers.bpm);
    }

    await user.save();
    console.log('🔍 [PLAN CONTROLLER] User updated with latest plan and BPM');

    res.json({ 
      plan,
      message: "Plan created successfully with BPM tracking"
    });
  } catch (err) {
    console.error("💥 [PLAN CONTROLLER] Error creating plan:", err.message);
    console.error("💥 [PLAN CONTROLLER] Error stack:", err.stack);
    res.status(500).json({ message: "Server error creating plan" });
  }
};

export const getUserDashboard = async (req, res) => {
  try {
    const userId = req.user.id;
    const user = await User.findById(userId)
      .select("-password")
      .populate("latestPlan");

    if (!user) {
      return res.status(404).json({ message: "User not found" });
    }

    // ✅ ENHANCED: Include BPM data in dashboard response
    const response = {
      user: {
        id: user._id,
        name: user.name,
        phone: user.phone,
        age: user.age,
        weight: user.weight,
        height: user.height,
        activity: user.activity,
        bpm: user.bpm, // ✅ BPM from user profile
        latestPlan: user.latestPlan
      }
    };

    console.log('🔍 [PLAN CONTROLLER] Dashboard data sent, user BPM:', user.bpm);
    res.json(response);
  } catch (err) {
    console.error("💥 Error fetching dashboard:", err.message);
    res.status(500).json({ message: "Server error fetching dashboard" });
  }
};